### ISSUE TITLE
Vue 2 (and Nuxt) support

### ISSUE THREAD

**Issue by productdevbook** [iWeltAG/pinia-cached-store#1]
vue 2 used nuxt now

**Comment by yrd** [comment]
What have you tried so far? This plugin is currently only compatible with Vue 3. Do you need the former version?

**Comment by productfrontenddeveloper** [comment]
Yes because used nuxt vue 2

**Comment by productfrontenddeveloper** [comment]
and `'defineCachedStore' is declared but its value is never read.ts(6133)` ts error

**Comment by productfrontenddeveloper** [comment]
defineCachedStore and this. problem 

![CleanShot 2021-08-23 at 19 14 53](https://user-images.githubusercontent.com/38668796/130481579-31d26a72-b2f9-4f7e-b656-0586433f2508.png)

**Comment by yrd** [comment]
I'm sorry, I can have a look later this week and see to get Vue 2 support working. And may I ask what you are trying to accomplish? Judging by your screenshot earlier you are trying to use actions with the cached store - which is not possible. Once you mark a store as caching it becomes read-only (with the exception of `$load()`).

**Comment by yrd** [comment]
@productfrontenddeveloper Have you gotten around to testing it yet?

**Comment by productfrontenddeveloper** [comment]
I haven't had a chance to test it yet.

**Comment by productdevbook** [comment]
iam sory we project change vue3/vite :/ dont tested
